spring.application.name=Gateway
server.port=8080

# --- USER SERVICE ---
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
# Remove o prefixo /user antes de enviar (transforma /user/auth em /auth)
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/user/(?<segment>.*), /$\{segment}

# --- PRODUCT SERVICE ---
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://Product
spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**
# Transforma /product/listAll em /products/listAll (ajustando o plural)
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/product/(?<segment>.*), /products/$\{segment}

# --- ORDER SERVICE ---
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://order
spring.cloud.gateway.routes[2].predicates[0]=Path=/order/**
# Transforma /order/listAll em /orders/listAll
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/order/(?<segment>.*), /orders/$\{segment}

# --- INVENTORY SERVICE ---
spring.cloud.gateway.routes[3].id=inventory-service
spring.cloud.gateway.routes[3].uri=lb://inventory
spring.cloud.gateway.routes[3].predicates[0]=Path=/inventory/**
# Aqui o nome já bate, então só limpamos o prefixo extra
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/inventory/(?<segment>.*), /inventory/$\{segment}

# --- PAYMENTS SERVICE ---
spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://Payments
spring.cloud.gateway.routes[4].predicates[0]=Path=/payments/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/payments/(?<segment>.*), /payments/$\{segment}
